stages:
  - Server_Start
  - Protocol_Tests

Server_Start:
  stage: Server_Start
  script:
    - echo "Testing that the python server runs..."
    - test -f app.py
    - timeout 2 python3 app.py 5001 || [[ $? -eq 124 ]]
  only:
    - Integration
    - main

Protocol_Tests:
  stage: Protocol_Tests
  script:
    - echo "Running test/python/runTests.sh..."
    - cd ./test/python/
    - bash -x runTests.sh
  only:
    - Integration
    - main